// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('Verifier')
const { proof, inputs } = require('../../zokrates/code/square/proof.json')
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('Verifier', accounts => {
    beforeEach(async () => {
        this.contract = await Verifier.new({ from: accounts[0] })
      }) 
// Test verification with incorrect proof
it('VerifyTx returns proof', async () => {
    const result = await this.contract.verifyTx.call(
        proof.a,
        proof.b,
        proof.c,
        inputs
    )
  console.log(`Result is:  ${result}`)
  assert(result)
  })
})